spring:
  datasource:
    url: "jdbc:mariadb://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:soukconect}?allowPublicKeyRetrieval=true&useSsl=false"
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: update   # automatically updates schema based on entities
    show-sql: true
  flyway:
    enabled: false       # disable Flyway until you need migrations
  main:
    allow-bean-definition-overriding: true
